### PR TITLE
fix(bridge-ui-v2): Bridged tokens do not require approval

### LINKED ISSUE #15509: Approve bug really big problem
### Describe the bug

While bridging from the katla network, I signed a transaction for 4 horse tokens, but after bridging 4 tokens, I realized that once I gave signature approval, I could bridge as many 4 horse tokens as I wanted. The other 4 horse tokens did not require signature approval for bridging transactions. 
approvebug
For the bug, follow these steps:
Bridge 4 horse tokens and then bridge 4 horse tokens again. When you do this, it will not ask for wallet confirmation to spend tokens for the 2nd transaction

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

### PR DESCRIPTION
**Pull request by KorbinianK**
- Canonical check util 
- Bypass approval checks before bridging

fixes #15509

### CODE REVIEW

File: packages/bridge-ui-v2/src/components/Bridge/Actions.svelte [hunk 1]
```diff
@@ -49,14 +50,19 @@
     bridge();
   }
 
-  onMount(() => {
+  onMount(async () => {
     $validatingAmount = true;
-    checkTokenApprovalStatus($selectedToken);
+    // await checkBridgedStatus();
```
Comment (KorbinianK) [inline packages/bridge-ui-v2/src/components/Bridge/Actions.svelte:55]:
```suggestion
```

**Review by davidtaikocha — APPROVED** [review]

**Review by dantaik — APPROVED** [review]
