### PR TITLE
fix(taiko-client): fallback proposer works when no active operator

### LINKED ISSUE #20600: Fallback proposer starts to work when no operator

### PR DESCRIPTION
**Pull request by YoGhurt111**

### CODE REVIEW

File: packages/taiko-client/pkg/rpc/methods.go [hunk 1]
```diff
@@ -1217,6 +1217,42 @@ func (c *Client) GetLastPacayaBatchID(ctx context.Context) (*big.Int, error) {
...
+	for i := uint8(0); i < count; i++ {
+		proposer, err := c.PacayaClients.PreconfWhitelist.OperatorMapping(opts, big.NewInt(int64(i)))
+		if err != nil {
+			return nil, fmt.Errorf("failed to get preconfirmation whitelist proposer by index %d: %w", i, err)
+		}
+		opInfo, err := c.PacayaClients.PreconfWhitelist.Operators(opts, proposer)
+		if err != nil {
+			return nil, fmt.Errorf("failed to get preconfirmation whitelist operator info: %w", err)
+		}
+		if opInfo.InactiveSince == 0 {
```
Comment (davidtaikocha) [inline packages/taiko-client/pkg/rpc/methods.go:1248]: Shall we change to check `opInfo.InactiveSince < currentTimestamp` here?

File: packages/taiko-client/proposer/proposer.go [hunk 2]
```diff
@@ -623,11 +623,21 @@ func (p *Proposer) shouldPropose(ctx context.Context) (bool, error) {
...
+		})
+		if err != nil {
+			return false, fmt.Errorf("failed to get all active preconfer address: %w", err)
+		}
+
+		// it needs to be either us, or the proverSet we propose through
+		if len(operators) != 0 ||
+			(fallbackPreconferAddress != p.proposerAddress &&
+				fallbackPreconferAddress != p.ProverSetAddress) {
+			log.Info("Preconfirmation is activated and proposer isn't the fallback preconfer, skip proposing",
```
Comment (davidtaikocha) [inline packages/taiko-client/proposer/proposer.go]:
```suggestion
			log.Info(
			  "Preconfirmation is activated and proposer isn't the fallback preconfer, skip proposing",
```

File: packages/taiko-client/pkg/rpc/methods.go [hunk 3]
```diff
@@ -1217,6 +1217,42 @@ func (c *Client) GetLastPacayaBatchID(ctx context.Context) (*big.Int, error) {
...
+	if err != nil {
+		return nil, fmt.Errorf("failed to get total preconfirmation whitelist operators: %w", err)
+	}
+
+	var operators []common.Address
+	for i := uint8(0); i < count; i++ {
+		proposer, err := c.PacayaClients.PreconfWhitelist.OperatorMapping(opts, big.NewInt(int64(i)))
+		if err != nil {
+			return nil, fmt.Errorf("failed to get preconfirmation whitelist proposer by index %d: %w", i, err)
+		}
```
Comment (MatusKysel) [inline packages/taiko-client/pkg/rpc/methods.go]:
```suggestion
	for i := 0; i < int64(count); i++ {
		proposer, err := c.PacayaClients.PreconfWhitelist.OperatorMapping(opts, big.NewInt(i)))
		if err != nil {
			return nil, fmt.Errorf("failed to get preconfirmation whitelist proposer by index %d: %w", i, err)
		}
```

File: packages/taiko-client/pkg/rpc/methods.go (hunk 1 above)
Comment (YoGhurt111) [reply packages/taiko-client/pkg/rpc/methods.go:1248]: After `removeOperator` call, the operator's `InactiveSince` != 0, so we can simple treat them as inactive.
If we want to get more accurate judgment, it should be `opInfo.InactiveSince > currentTimestamp`.

**Review by davidtaikocha — APPROVED** [review]

**Review by MatusKysel — APPROVED** [review]
