### PR TITLE
fix(bridge): fix max amount button

### LINKED ISSUE #2743: bug(bridge-ui): Max features not working properly
### Describe the bug

Max features not working

### Steps to reproduce

1) Go to https://bridge.a1.taiko.xyz/
2) Bridge ETH A1 to TAIKO A1
3) Click Max Features

Max features not working

image

### Additional context

Wallet used for testnet
0x5D9D12C6D996cce9B6B4AaDD8D3d4F81B0465e8d

### PR DESCRIPTION
**Pull request by shadab-taiko**
Fixes [#2743](https://github.com/taikoxyz/taiko-mono/issues/2743)

### CODE REVIEW

**Review by dionysuzx — DISMISSED** [review]

File: packages/bridge-ui/src/components/form/BridgeForm.svelte [hunk 1]
```diff
@@ -289,6 +291,7 @@
       on:input={updateAmount}
       class="input input-primary bg-dark-4 input-md md:input-lg w-full focus:ring-0"
       name="amount"
+      bind:this={amountInput}
```
Comment (WormydogDOTeth) [inline packages/bridge-ui/src/components/form/BridgeForm.svelte:294]: So would it not be wise to bind amount here and then use same function to update the input?

**Comment by dantaik** [comment]
@shadab-taiko can we make sure the accuracy of the max value is a fixed value.

File: packages/bridge-ui/src/components/form/BridgeForm.svelte [hunk 2]
```diff
@@ -273,7 +275,7 @@
       <button class="label-text" on:click={useFullAmount}
         >{$_("bridgeForm.maxLabel")}
         {tokenBalance.length > 10
-          ? `${truncateString(tokenBalance)}...`
+          ? `${truncateString(tokenBalance, 6)}...`
```
Comment (dantaik) [inline packages/bridge-ui/src/components/form/BridgeForm.svelte:278]: A better approach is to use `toFixed(4)`

https://ethereum.stackexchange.com/questions/84004/ethers-formatetherwei-with-max-4-decimal-places

Comment (shadab-taiko) [reply packages/bridge-ui/src/components/form/BridgeForm.svelte:278]: I see some trade-offs here.
1. `tokenBalance` contains `string` type value. So to use `toFixed` it will have to be first converted to a `number` type.
2. `toFixed` pads the decimal side with additional zeroes if the number of digits in the number is less than the required number of digits. For example, 5.8 becomes 5.8000.

Thus with the current `truncateString` util function we are free from any type conversions and unnecessary zero padding of the decimal side.

Let me know what you think @dantaik ?

**Review by dantaik — APPROVED** [review]

**Review by dionysuzx — APPROVED** [review]
