### PR TITLE
fix(taiko-client-rs): add TTL cache for whitelist sequencer lookups

### LINKED ISSUE #21293: feat(taiko-client-rs): cache whitelist lookahead in `whitelist-preconfirmation-driver`
ref: https://github.com/taikoxyz/taiko-mono/pull/21289

### PR DESCRIPTION
**Pull request by MatusKysel**
…quencer lookups

Cache current/next whitelist sequencer addresses with a 12-second TTL (one L1 slot) to avoid 4 on-chain RPC calls per incoming gossip message.

On signer mismatch, only invalidate and re-fetch from L1 when cached values were served from cache (could be stale due to epoch rotation). When values were freshly fetched, reject immediately to prevent spam from bypassing the cache and saturating the L1 RPC.

Fixes https://github.com/taikoxyz/taiko-mono/issues/21293

### CODE REVIEW

File: packages/taiko-client-rs/crates/whitelist-preconfirmation-driver/src/cache.rs [hunk 1]
```diff
@@ -17,6 +17,10 @@ const DEFAULT_RECENT_ENVELOPE_CAPACITY: usize = 1024;
 const DEFAULT_PENDING_ENVELOPE_CAPACITY: usize = 768;
 /// Default cooldown, in seconds, between duplicate parent-hash requests.
 const DEFAULT_REQUEST_COOLDOWN_SECS: u64 = 10;
+/// Default TTL for cached whitelist sequencer addresses (one L1 slot).
+const DEFAULT_SEQUENCER_CACHE_TTL_SECS: u64 = 12;
```
Comment (davidtaikocha) [inline packages/taiko-client-rs/crates/whitelist-preconfirmation-driver/src/cache.rs]: For the whitelist preconfirmation, sequencer selection is based on epoch, so shall we change here to `12 * 32`?

Comment (MatusKysel) [reply packages/taiko-client-rs/crates/whitelist-preconfirmation-driver/src/cache.rs]: fixed [252bce0](https://github.com/taikoxyz/taiko-mono/pull/21299/commits/252bce02b7ff831daf29002b4002cc8ee7b27c2c)

**Review by davidtaikocha — APPROVED** [review]

**Review by johntaiko — APPROVED** [review]

**Review by YoGhurt111 — APPROVED** [review]
