### PR TITLE
fix(taiko-client): stalled finalized block height

### LINKED ISSUE #21521: fix(taiko-client): stalled finalized block height

### PR DESCRIPTION
**Pull request by YoGhurt111**

### CODE REVIEW

File: packages/taiko-client/driver/chain_syncer/event/blocks_inserter/common.go [hunk 1]
```diff
@@ -938,7 +939,32 @@ func InsertPreconfBlockFromEnvelope(
 
 	payloadID := args.Id()
 
-	var u256BaseFee = uint256.Int(envelope.Payload.BaseFeePerGas)
+	var (
+		u256BaseFee    = uint256.Int(envelope.Payload.BaseFeePerGas)
+		safeCheckpoint *verifiedCheckpoint
+	)
+
+	if envelope.Payload.Timestamp >= eth.Uint64Quantity(cli.ShastaClients.ForkTime) {
```
Comment (davidtaikocha) [inline packages/taiko-client/driver/chain_syncer/event/blocks_inserter/common.go:949]: Shall we [clean up Pacaya](https://github.com/taikoxyz/taiko-mono/issues/21482) first in `taiko-client` first? So we don't need to worry about this anymore going forward.

File: packages/taiko-client/driver/chain_syncer/event/blocks_inserter/common.go [hunk 2]
```diff
@@ -938,7 +939,32 @@ func InsertPreconfBlockFromEnvelope(
...
+			cli.L2.HeaderByNumber,
+		)
+		if err != nil {
+			return nil, err
+		}
+	} else {
+		lastVerifiedTS, err := cli.GetLastVerifiedTransitionPacaya(ctx)
+		if err != nil {
+			return nil, fmt.Errorf("failed to fetch last verified block: %w", err)
+		}
```
[the remark this answers is not in the document]
Comment (YoGhurt111) [reply packages/taiko-client/driver/chain_syncer/event/blocks_inserter/common.go]: Fixed in https://github.com/taikoxyz/taiko-mono/pull/21523/changes/c363b25dce8b89187455987850cee6f18986c071

**Comment by YoGhurt111** [comment]
@claude Plz review again

**Comment by YoGhurt111** [comment]
@claude Plz review, reduced the frequency of eth call.

File: packages/taiko-client/driver/chain_syncer/event/blocks_inserter/common.go (hunk 1 above)
Comment (YoGhurt111) [reply packages/taiko-client/driver/chain_syncer/event/blocks_inserter/common.go:949]: IMO, it would be better to roll out this fix as soon as possible.

**Review by davidtaikocha — APPROVED** [review]

**Review by RogerLamTd — APPROVED** [review]
