### PR TITLE
fix(status-page): latest proof time

### LINKED ISSUE #13503: fix (status-pagr): Latest Proof Tile Shows Wed Dec 31 1969
### Describe the bug

Watching the Taiko Status page (<https://status.a2.taiko.xyz/>), occasionally the `Latest Proof` date/time shows:

Screenshot 2023-03-30 at 8 39 09 AM

### Steps to reproduce

Head over to <https://status.a2.taiko.xyz/> and watch the Latest Proof tile.

### Additional context

Additional context here.

### PR DESCRIPTION
**Pull request by shadab-taiko**
@cyberhorsey can you check if this fixes #13503 ?

### CODE REVIEW

**Review by cyberhorsey — APPROVED** [review]

File: packages/status-page/src/pages/home/Home.svelte [hunk 1]
```diff
@@ -253,10 +253,12 @@
           const contract = new Contract(address, TaikoL1, provider);
           contract.on(
             "BlockProven",
-            (id, parentHash, blockHash, prover, provenAt) => {
+            (id, parentHash, blockHash, prover, provenAt, ...args) => {
               // ignore oracle prover
               if (prover.toLowerCase() !== oracleProverAddress.toLowerCase()) {
-                onEvent(new Date(provenAt.toNumber() * 1000).toString());
+                if(!provenAt.eq(0)) {
```
Comment (dantaik) [inline packages/status-page/src/pages/home/Home.svelte:259]: `provenAt.ne(0)`?

**Review by davidtaikocha — APPROVED** [review]
